# Values for the dev environment. This is the environment that was actually
# applied against a real account, so these are the settings the README of the
# project describes.
#
# This file is committed on purpose. It is the definition of the environment,
# and there is nothing secret in it: the database password is generated by RDS
# and stored in Secrets Manager, and AWS credentials come from the provider
# credential chain.

aws_region         = "eu-west-2"
availability_zones = ["eu-west-2a", "eu-west-2b"]

name_prefix = "project4-dev"

vpc_cidr            = "10.0.0.0/16"
public_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
app_subnet_cidrs    = ["10.0.3.0/24", "10.0.4.0/24"]
db_subnet_cidrs     = ["10.0.5.0/24", "10.0.6.0/24"]

# One NAT Gateway, shared by both zones. Cheapest, and a single point of
# failure for outbound traffic.
single_nat_gateway = true

instance_type = "t3.micro"

asg_min_size         = 2
asg_desired_capacity = 2
asg_max_size         = 4

db_engine_version    = "8.0"
db_instance_class    = "db.t4g.micro"
db_allocated_storage = 20
db_name              = "appdb"
db_username          = "admin"

# True, as deployed. It roughly doubles the database cost, which is the
# trade-off being made for a failover that stays behind the same endpoint.
db_multi_az = true

# False, as deployed. Encryption at rest can only be turned on at creation, so
# in prod this is true from the first apply and never a later fix.
db_storage_encrypted = false

db_backup_retention_period = 1
db_skip_final_snapshot     = true
db_deletion_protection     = false

# alert_email is deliberately not set here: an unset address creates no
# subscription, which is the safe default for a public repository.
cpu_alarm_threshold = 70
log_retention_days  = 7

common_tags = {
  Project     = "Project4"
  Environment = "dev"
  ManagedBy   = "Terraform"
}
